### ISSUE TITLE
Support data persistent: integrate with storageClass

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd-operator#28]
The goal is to ensure the etcd's data will not get lost once the VM or POD is rebooted.

So we need to support setting `VolumeClaimTemplate` for the statefulset, something like below,

```
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "csi-sc-standard"
      resources:
        requests:
          storage: 32Gi
```

Note that it isn't etcd-operator's responsibility to provision / manage the CSI driver in production environment. 

But we need to provision / manage a CSI driver for our test environment, 
- one possible solution that I can think of is [openebs localpv](https://github.com/openebs/dynamic-localpv-provisioner/tree/develop/deploy/kubectl). 
- or [csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path) for single node test environment. 
- or use hostPath directly, something like below,

   ```
    volumes:
    - name: my-data
      hostPath:
        path: /data/${POD_NAME}
        type: DirectoryOrCreate
   ```

I am open to other alternatives.

**Comment by ahrtr** [comment]
This isn't a good first issue. It needs some experience on K8s and PV/PVC/StorageClass.

**Comment by liangyuanpeng** [comment]
> But we need to provision / manage a CSI driver for our test environment,

etcd-operator is using Kind for CI, and Kind including a local path provider, so i think just use local-path provider from Kind is enough?

```shell
$ k get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  15m
```

**Comment by ahrtr** [comment]
I think that it would be better to support both file system and block volume. We leave it to users to use what kind of storage, but we need to ensure the configuration is flexible.

If users do not configure any storage, then we just use the container's default temporary storage; it will be useful for users to do quick evaluation or experiment in their test environment.

Specifically, users should be able to configure `volumes` or `volumeClaimTemplates`.

If users configure a volume, then it's shared by all PODs. In that case, we need to create a sub directory to avoid conflict. See example below. Usually it's the use case of file system storage, i.e. NFS. The administrator needs to provision & manage the PVC/PV themselves.
```
      containers:
        - name: etcd
          volumeMounts:
          - name: etcd-data-shared
            mountPath: /var/lib/etcd
            subPathExpr: $(POD_NAME)            
      volumes:
      - name: etcd-data-shared
        persistentVolumeClaim:
          claimName: etcd-pvc-shared
```

If users configure a `VolumeClaimTemplate`,  then a PV is dynamically created (by the CSI driver) for each POD.  Usually it's the use case of block volume storage. See example below,

```
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "csi-sc-standard"
      resources:
        requests:
          storage: 32Gi

For the volumeMounts, we don't need to use subPath, nor `subPathExpr`. 
But to keep it as simple as possible, we can keep it consistent with the volumes case above.
```

For now, we can define a struct `StorageSpec`, something like below. In future, we might need to provide more flexibility, to let users configure the `volumes` and `VolumeClaimTemplate` directly, just as how they configure a statefulsets directly.
```
type StorageSpec struct {
    AccessModes string // `ReadWriteOnce` (default) or `ReadWriteMany`. Note that `ReadOnlyMany` isn't allowed.
    StorageClassName string // optional, the default one will be used if not specified
    VolumeSize resource.Quantity // required.
}
```

and add a field `Storage *StorageSpec` into `EtcdClusterSpec`.
- If the `AccessModes` is `ReadWriteMany`, then we define the `volumes`.
- If  the `AccessModes` is `ReadWriteOnce` (it's also the default option), then we define a `VolumeClaimTemplate`.
- If users do not configure `StorageSpec` at all, then each POD just uses the temporary storage inside the container. As mentioned above, It's not recommended in production, but will be useful for users to evaluate or experiment the etcd operator.

**Comment by gdasson** [comment]
Please assign

**Comment by ahrtr** [comment]
@gdasson are you still working on this?

**Comment by luismacosta** [comment]
> I think that it would be better to support both file system and block volume. We leave it to users to use what kind of storage, but we need to ensure the configuration is flexible.
> 
> If users do not configure any storage, then we just use the container's default temporary storage; it will be useful for users to do quick evaluation or experiment in their test environment.
> 
> Specifically, users should be able to configure `volumes` or `volumeClaimTemplates`.
> 
> If users configure a volume, then it's shared by all PODs. In that case, we need to create a sub directory to avoid conflict. See example below. Usually it's the use case of file system storage, i.e. NFS. The administrator needs to provision & manage the PVC/PV themselves.
> 
> ```
>       containers:
>         - name: etcd
>           volumeMounts:
>           - name: etcd-data-shared
>             mountPath: /var/lib/etcd
>             subPathExpr: $(POD_NAME)            
>       volumes:
>       - name: etcd-data-shared
>         persistentVolumeClaim:
>           claimName: etcd-pvc-shared
> ```
> 
> If users configure a `VolumeClaimTemplate`, then a PV is dynamically created (by the CSI driver) for each POD. Usually it's the use case of block volume storage. See example below,
> 
> ```
>   volumeClaimTemplates:
>   - metadata:
>       name: etcd-data
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       storageClassName: "csi-sc-standard"
>       resources:
>         requests:
>           storage: 32Gi
> 
> For the volumeMounts, we don't need to use subPath, nor `subPathExpr`. 
> But to keep it as simple as possible, we can keep it consistent with the volumes case above.
> ```
> 
> For now, we can define a struct `StorageSpec`, something like below. In future, we might need to provide more flexibility, to let users configure the `volumes` and `VolumeClaimTemplate` directly, just as how they configure a statefulsets directly.
> 
> ```
> type StorageSpec struct {
>     AccessModes string // `ReadWriteOnce` (default) or `ReadWriteMany`. Note that `ReadOnlyMany` isn't allowed.
>     StorageClassName string // optional, the default one will be used if not specified
>     VolumeSize resource.Quantity // required.
> }
> ```
> 
> and add a field `Storage *StorageSpec` into `EtcdClusterSpec`.
> 
> * If the `AccessModes` is `ReadWriteMany`, then we define the `volumes`.
> * If  the `AccessModes` is `ReadWriteOnce` (it's also the default option), then we define a `VolumeClaimTemplate`.
> * If users do not configure `StorageSpec` at all, then each POD just uses the temporary storage inside the container. As mentioned above, It's not recommended in production, but will be useful for users to evaluate or experiment the etcd operator.

Hello,

If If the `AccessModes` is `ReadWriteMany`, VolumeClaimTemplate should also be created, in case users want to define storageClassName a nfs, in order to use [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master) to create the access points in Amazon EFS file system

**Comment by ahrtr** [comment]
> f the `AccessModes` is `ReadWriteMany`, VolumeClaimTemplate should also be created, in case users want to define storageClassName as nfs, in order to use [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master) to create the access points in Amazon EFS file system

Theoretically it's true, but in practice I am not much concern about it.
 
I don't think the nfs is recommended to store etcd's data.
- performance concern.  network IO latency and disk IO latency are very important for etcd. NFS would introduce more delay on network transportation.
- more importantly, NFS might not guarantee/follow `fsync`, so it may cause correctness issue.

**Comment by SDBrett** [comment]
The current implementation is functional but only having 1 PV for all pods is not ideal for the long run. I agree with @luismacosta that it would be good to provide users with the ability to specify `volumes` and `volumeClaimTemplates` in a future release.

To add `VolumeClaimTemplates` in a future release could be done by refactoring `StorageSpec` so the CR would like something like

```
StorageSpec:
  Volumes:
    - Array of Volumes
  VolumeClaimTemplates:
    - Array of VolumeClaimTemplates
```

On the topic of certain storage options not being suitable for ETCD for various reasons, I do not feel that the operator should decide if a storage option is appropriate for ETCD as it would add a lot of complexity and technical debt. 

I feel that the operator documentation should like to ETCD best practices on storage and pass the configuration through to the statefullSet configuration.
