### ISSUE TITLE
Plan to release v0.1.0

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd-operator#92]
We're preparing to release the first version of the etcd-operator (v0.1.0). This issue tracks the work discussed during the etcd-operator WG meeting.

### Outstanding tasks before releasing this version:

- [x] ~Create a new artifact registry under etcd-development (@ivanvc)~
    - No need: we just need to tag a new image `gcr.io/etcd-development/etcd-operator:SHA` and do a Docker push and that will create the registry (I already tested this).
- [x] Minimal script to build a release, tagging + Docker image push (nice to have/@ivanvc)
  - #100
- [x] Documentation on how to deploy the operator
- ~#9~

**Comment by ahrtr** [comment]
> * Documentation on how to deploy the operator

I think this might be the most important for now. If the certificate PR isn't able to be merged before KubeCon London, we can also release v0.1.0 with what we already have. Specifically,
- We need provide detailed guide & steps on how to deploy etcd-operator;
- We need to provide some example configs on how to use CSI Drivers

**Comment by ivanvc** [comment]
I would suggest that someone with more knowledge of the codebase works on the installation guide. I don't want to commit to helping with that, as I may be unable to finish the other tasks.

**Comment by ivanvc** [comment]
@ahrtr, should we cut a new `release-0.1` branch? Or, given we're not at the 1.0.0 major, should we keep the work on the main branch?

**Comment by ahrtr** [comment]
@ivanvc  I don't think we need to cut the release-0.1 branch until v1.0.0. We only cut branches for stable/LTS releases.

Even when we release v1.0.0, we don't have to necessarily cut release-v1.0. It depends on how we manage the releases. But we can discuss it by then.

**Comment by ahrtr** [comment]
See an example on how to configure CSI, cc @gdasson @ivanvc 

```
apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-sample
spec:
  size: 3
  version: "v3.5.20"
  storageSpec:
    accessModes: "ReadWriteOnce"  # Note that 'ReadWriteOnce' is the default option, so users don’t need to configure it explicitly.
    storageClassName: "standard"
    volumeSizeRequest: "8Gi"

```
